SET FOREIGN_KEY_CHECKS=0;


INSERT INTO `chapters` (`name`,`chapter_id`)
VALUES
  ("Central Kalimantan",1),
  ("Trà Vinh",2),
  ("Kostroma Oblast",3),
  ("Drenthe",4),
  ("Ceará",5),
  ("Nova Scotia",6),
  ("Lower Austria",7),
  ("Tuyên Quang",8),
  ("Podkarpackie",9),
  ("Karnataka",10),
  ("Lorraine",11),
  ("Utrecht",12),
  ("Oost-Vlaanderen",13),
  ("Boyacá",14),
  ("Prince Edward Island",15),
  ("Catalunya",16),
  ("Western Australia",17),
  ("Rivers",18),
  ("Pays de la Loire",19),
  ("Paraná",20),
  ("Osun",21),
  ("Västra Götalands län",22),
  ("Sardegna",23),
  ("Luik",24),
  ("Bremen",25),
  ("Zhōngnán",26),
  ("Maryland",27),
  ("Henegouwen",28),
  ("North Island",29),
  ("Dalarnas län",30),
  ("Comunitat Valenciana",31),
  ("Dolnośląskie",32),
  ("Östergötlands län",33),
  ("Zuid Holland",34),
  ("Comunitat Valenciana",35),
  ("Toscana",36),
  ("Tasmania",37),
  ("Punjab",38),
  ("Pays de la Loire",39),
  ("British Columbia",40),
  ("Lancashire",41),
  ("Berlin",42),
  ("Oslo",43),
  ("Illes Balears",44),
  ("FATA",45),
  ("Saskatchewan",46),
  ("Jönköpings län",47),
  ("Omsk Oblast",48),
  ("Munster",49),
  ("Ulster",50);

SET FOREIGN_KEY_CHECKS=1;