SET FOREIGN_KEY_CHECKS=0;


INSERT INTO `chapters` (`name`,`chapter_id`)
VALUES
  ("Central Kalimantan",1),
  ("Trà Vinh",2),
  ("Kostroma Oblast",3),
  ("Drenthe",4),
  ("Ceará",5),
  ("Nova Scotia",6),
  ("Lower Austria",7),
  ("Tuyên Quang",8),
  ("Podkarpackie",9),
  ("Karnataka",10),
  ("Lorraine",11),
  ("Utrecht",12),
  ("Oost-Vlaanderen",13),
  ("Boyacá",14),
  ("Prince Edward Island",15),
  ("Catalunya",16),
  ("Western Australia",17),
  ("Rivers",18),
  ("Pays de la Loire",19),
  ("Paraná",20),
  ("Osun",21),
  ("Västra Götalands län",22),
  ("Sardegna",23),
  ("Luik",24),
  ("Bremen",25),
  ("Zhōngnán",26),
  ("Maryland",27),
  ("Henegouwen",28),
  ("North Island",29),
  ("Dalarnas län",30),
  ("Comunitat Valenciana",31),
  ("Dolnośląskie",32),
  ("Östergötlands län",33),
  ("Zuid Holland",34),
  ("Comunitat Valenciana",35),
  ("Toscana",36),
  ("Tasmania",37),
  ("Punjab",38),
  ("Pays de la Loire",39),
  ("British Columbia",40),
  ("Lancashire",41),
  ("Berlin",42),
  ("Oslo",43),
  ("Illes Balears",44),
  ("FATA",45),
  ("Saskatchewan",46),
  ("Jönköpings län",47),
  ("Omsk Oblast",48),
  ("Munster",49),
  ("Ulster",50);

INSERT INTO `client_users` (`name`,`email`,`role_id`,`verified`,`oauth`)
VALUES
  ("Stone Rivera","elementum.purus@hotmail.org",0,0,0),
  ("Imogene Rosa","et.netus@icloud.net",0,0,0),
  ("Sade Bowers","vulputate.eu@aol.ca",0,0,0),
  ("Hammett Moon","lorem.eget@hotmail.ca",0,0,0),
  ("Len Salinas","sociis.natoque@outlook.com",0,0,0),
  ("Gwendolyn Dillard","nam@aol.org",0,0,0),
  ("Leandra Valentine","cum.sociis.natoque@hotmail.net",0,0,0),
  ("Sebastian Meyers","eget@icloud.couk",0,0,0),
  ("Aristotle Burris","in.scelerisque@outlook.couk",0,0,0),
  ("Amos Spence","morbi.accumsan@google.ca",0,0,0),
  ("Ezekiel Sullivan","blandit.mattis.cras@aol.edu",0,0,0),
  ("Caesar Case","nibh.enim@outlook.edu",0,0,0),
  ("Cooper Hill","malesuada@yahoo.net",0,0,0),
  ("Grace Sanchez","enim.nec.tempus@icloud.org",0,0,0),
  ("Thane Townsend","tincidunt.aliquam@yahoo.ca",0,0,0),
  ("Cheyenne Bridges","tellus.faucibus@hotmail.org",0,0,0),
  ("Jolene Dawson","nunc.quis@aol.com",0,0,0),
  ("Marny Pearson","quisque.porttitor@outlook.edu",0,0,0),
  ("Knox Heath","faucibus.leo@aol.ca",0,0,0),
  ("Herrod Wheeler","magna.praesent@google.couk",0,0,0),
  ("Fallon Carr","enim.consequat.purus@yahoo.couk",0,0,0),
  ("Jakeem Patterson","sollicitudin@outlook.com",0,0,0),
  ("Genevieve Norton","parturient.montes@outlook.org",0,0,0),
  ("Faith Rojas","massa@google.edu",0,0,0),
  ("India Johns","eu.augue@protonmail.ca",0,0,0),
  ("Carter Davenport","metus.vivamus@google.net",0,0,0),
  ("Fleur Orr","placerat.orci@outlook.edu",0,0,0),
  ("Lisandra Mcmahon","integer.id@yahoo.edu",0,0,0),
  ("Ivan Valentine","a.tortor@protonmail.net",0,0,0),
  ("Ebony Joyner","et@aol.com",0,0,0),
  ("Whoopi Knight","pellentesque@protonmail.edu",0,0,0),
  ("Anastasia Knox","elit.nulla@protonmail.net",0,0,0),
  ("Igor Hendricks","scelerisque.neque@icloud.org",0,0,0),
  ("Cassady Frye","auctor@google.org",0,0,0),
  ("Halla Mcfarland","integer.id.magna@outlook.net",0,0,0),
  ("Kenyon Herrera","donec.non.justo@yahoo.net",0,0,0),
  ("Tobias Parker","sociis.natoque.penatibus@protonmail.ca",0,0,0),
  ("Remedios Walton","sociis.natoque@yahoo.com",0,0,0),
  ("Stuart Hinton","dolor.vitae@hotmail.ca",0,0,0),
  ("Freya Nielsen","donec@outlook.edu",0,0,0),
  ("Mikayla Dillard","sem.magna@aol.com",0,0,0),
  ("Reuben Moon","arcu.ac@outlook.net",0,0,0),
  ("Carol Rojas","at.risus@yahoo.couk",0,0,0),
  ("Emery Forbes","eu.euismod@google.couk",0,0,0),
  ("Megan Murphy","suspendisse.aliquet@google.org",0,0,0),
  ("Acton Riddle","cubilia@yahoo.net",0,0,0),
  ("Colin Burt","curabitur.consequat@aol.net",0,0,0),
  ("Price Stone","posuere.at@google.net",0,0,0),
  ("Alfonso Jenkins","gravida.sit.amet@yahoo.ca",0,0,0),
  ("Kermit Randall","ipsum.suspendisse@icloud.com",0,0,0);


SET FOREIGN_KEY_CHECKS=1;